### ISSUE TITLE
list in python

### ISSUE THREAD

**Issue by ishaan010** [ishaan010/ezpie#13]
Need help for making a webpage about list in python

**Comment by Beatrix-droid** [comment]
can you please assign this to me please?

**Comment by ishaan010** [comment]
I never thought that anyone will help! your help is like help of a god for me! thanks a lot.

**Comment by Beatrix-droid** [comment]
> I never thought that anyone will help! your help is like help of a god for me! thanks a lot.

You are most most welcome! Yours is a good idea, and I support the concept a website that teaches the basics of python for free. The plan is to get your issue sorted by this evening at  the latest. 

In return when you have time, could you help me out with this issue?

https://github.com/Beatrix-droid/LAN_chatting_app/issues/4

Is not difficult, just use the contribution.md file from the Ruby on Rails documentation (linked in the issue) and substitute my project name and contact email in the place of the Ruby on Rails name and contact email

**Comment by ishaan010** [comment]
Yes I would love to help someone who is helping me
