### ISSUE TITLE
Like to contribute? then click here!

### ISSUE THREAD

**Issue by ishaan010** [ishaan010/ezpie#16]
Get started to contribute by helping in creating a webpage about list in python. For more detail leave a comment or leave a message at 
[here](https://mail.google.com/mail/u/0/#inbox?compose=GTvVlcSKjfscsdlwfwRLtmkstLjTxPvQpSgWngjzNxfkkxMWljPRlTxQnMHBqkJVBmsSvDwQVRbbX)

**Comment by debjit20504** [comment]
HI, I'd like to help :)

**Comment by ishaan010** [comment]
Hi, if you like to help then first tell in which programming language you are good at.

**Comment by debjit20504** [comment]
> Hi, if you like to help then first tell in which programming language you are good at.

currently, I'm using java, python and learning javascript

**Comment by ishaan010** [comment]
OK therefore you can help in making a webpage about list in python and first [read this](https://github.com/ishaan010/ezpie/blob/master/CONTRIBUTING.md) so you wont have any problems

**Comment by ishaan010** [comment]
And also first visit the [beta version](https://ishaan010.github.io/ezpie/tutorials/python/flow/statement.html) so you have a detail idea of how to help
