### ISSUE TITLE
Make a webpage for modules in python

### ISSUE THREAD

**Issue by ishaan010** [ishaan010/ezpie#29]
If you are good at python then try to make a webpage for modules in python. For a better understanding of ezpie's work style please go [here](https://github.com/ishaan010/ezpie/blob/master/CONTRIBUTING.md). Please tell so I can make a branch for you to work in!

**Comment by SaarthakMaini** [comment]
I can make the web page for modules in python. Could you please let me know where exactly I have to make the web page in the repository? Thank you!

**Comment by ishaan010** [comment]
Yes, you have to make the webpage here:
![image](https://user-images.githubusercontent.com/104765117/184147494-101c8add-7287-4cc6-8759-64cffbc23bc3.png)
inside the function folder.

**Comment by ishaan010** [comment]
If you have any further doubt then do ask. Thank you

**Comment by ishaan010** [comment]
I created a branch for you, make pull request in that branch only.

**Comment by SaarthakMaini** [comment]
Great! I'll start working on it
