### ISSUE TITLE
Not an organized footer

### ISSUE THREAD

**Issue by hs-07** [ishaan010/ezpie#31]
I saw the application and analysied it a bit and would like to raise an issue regarding the footer design. It looks very _unorganised_.

![Screenshot (5)](https://user-images.githubusercontent.com/87127387/184171105-570e0265-92de-410c-a5ae-eb2085b53480.png)

**I would love to design it properly and contributing in the project.**
**I will not only make it look organised but also responsive.**
**Thus request you to assign the issue to me. Waiting for the response.**

**Comment by ishaan010** [comment]
Yes you can do it
