### ISSUE TITLE
Markdown Error In README documentation

### ISSUE THREAD

**Issue by SaarthakMaini** [ishaan010/ezpie#32]
**Describe the bug**
In the README file, the link given for Freecodecamp is not behaving properly. 

**To Reproduce**
1. Go to the [README file](https://github.com/ishaan010/ezpie/blob/master/README.md)
1. See the error mentioned above

**Expected behavior**
The URL of the link should not be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/94912101/184309755-a0a23f77-d901-4bfc-a6af-39c582a8c094.png)

**Comment by ishaan010** [comment]
OK, right now I am working on something else so can you quickly make a pull request?

**Comment by SaarthakMaini** [comment]
Sure! On it!

**Comment by SaarthakMaini** [comment]
Pull Request : #34
