### ISSUE TITLE
Markdown Error For Issue Link In README documentation

### ISSUE THREAD

**Issue by SaarthakMaini** [ishaan010/ezpie#33]
**Describe the bug**
In the README file, the link given for issue is not behaving properly.

**To Reproduce**
1. Go to [README](https://github.com/ishaan010/ezpie/blob/master/README.md)
2. See the error mentioned above

**Expected behavior**
The URL of the link should not be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/94912101/184311039-f1eedaff-27a2-48ed-b4d1-b6ae33d4a473.png)

**Comment by ishaan010** [comment]
Please make a pull request for that
