### ISSUE TITLE
Report borken links

### ISSUE THREAD

**Issue by ishaan010** [ishaan010/ezpie#53]
# Check our site Ezpie for broken links
This issue is for [HackToberFest 2022](https://hacktoberfest.com)

Follow these steps to report the list of broken links:

## 📋 Steps

- [ ] Visit the site at [Ezpie](https://ishaan010.github.io/ezpie)
- [ ] Click at links to see if they are working or not
- [ ] If a link is working then see for links which are not in the other pages
- [ ] Once you are done, you can copy and paste this format at your new issue:
```
# Report of broken links

1.  URL of broken link - 
image of broken link

2. Repeat for rest

```

## Any issues?
If you have any issue, small or big, you can always ask for help 😄. I would be happy to help you in your hacktoberfest contribution 😀

**Comment by Bhavil-13** [comment]
Can you assign it to me? @ishaan010

**Comment by ishaan010** [comment]
Yes this is all your @Bhavil-13. If you have any problems while working out you can always ask for help.
Happy hacktoberfesting! 😆

**Comment by Bhavil-13** [comment]
Did i have to create a new issue? I think I created a new issue

**Comment by ishaan010** [comment]
Yes you have to create a new issue with the given format, so it's easy for me to read and easy for you to give
