### ISSUE TITLE
#Report of new issues

### ISSUE THREAD

**Issue by Bhavil-13** [ishaan010/ezpie#54]
[brokenLinkReport.pdf](https://github.com/ishaan010/ezpie/files/9844331/brokenLinkReport.pdf)

**Comment by ishaan010** [comment]
Thanks for your help 😄 Why don't you make a PR for the fix and don't worry about the challenge links, they will show this tell ezpie have not reach at lest 1000 views(you know the same 'get more viewers') for links related to github you can find them in my repositories tab. do be quick so I can give you a **hacktoberfest-accepted** label 😃

**Comment by ishaan010** [comment]
Quick thing, would you like to join me and @ngdream at ezpie to help lots of new developer reach their dreams? If yes do tell I will add you as a collaborator

**Comment by Bhavil-13** [comment]
yeah sure, it will be amazing. Also, I tried to push my changes, but it's saying permission denied, can you help?

**Comment by ishaan010** [comment]
That's because of protection, you just join ezpie you need to get used to the style of writing html code here that's why. And first you will need to do a PR on another branch then I will check for any errors then I will create a PR to merge it into the master branch.

**Comment by ngdream** [comment]
Ok

**Comment by ngdream** [comment]
i'm working on it right now
