### ISSUE TITLE
add meta tags for description and keywords in your index.html

### ISSUE THREAD

**Issue by ngdream** [ishaan010/ezpie#57]
please add a description on your site

**Comment by ishaan010** [comment]
Oh yes I forgot about it, but right now I can't as I am making a vs code extension for searching blogs in ezpie, so please can you add the meta tags

**Comment by ishaan010** [comment]
Oh and he is not good at web development so just tell him how it's done

**Comment by Bhavil-13** [comment]
thanks for assigning this to me, also, I'm sorry for the late reply

**Comment by VijendraPandey** [comment]
Hello @ishaan010 I would like to work on this issue. If it is still open do assign it to me. Thanks.

**Comment by ishaan010** [comment]
Ok @VijendraPandey  you can do this issue, but make a PR only in the issues branch

**Comment by VijendraPandey** [comment]
Thanks @ishaan010. I have made the PR. Please verify it and if there are any corrections required then please tell me.

**Comment by ishaan010** [comment]
OK
