### ISSUE TITLE
Ezpie in newer styles

### ISSUE THREAD

**Issue by ishaan010** [ishaan010/ezpie#65]
Hey @ngdream and @Bhavil-13, I think we should convert ezpie into using jekyll.
if you will be comfortable with it do tell.

If there be any problems create an issue and put it in the **new ezpie milestone**.

**Comment by ngdream** [comment]
i'm already working on it as you know

**Comment by ngdream** [comment]
@ishaan010  check my work here  https://github.com/ngdream/ezpie

**Comment by ishaan010** [comment]
Ya looks good, but I think you should try using a bit more layouts, cause we are just repeating the code again in the **posts**.
Try this in the layout for _main.html_:
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/home.css">
    <link rel="icon" type="image/x-icon" href="asset/logo/profile.png">

    <title>{{ page.title }}</title>
</head>

<body>
    {% include nav.html %}

    {{ content }}

    {% include footer.html %}

    <script src="javascript/sideNav.js"></script>
    <script src="javascript/search.js"></script>
</body>

</html>
```

To make thinks easier to access we can use the **_includes** for footer and nav.

Wait I will just merge my code then you can pull it and get into working with the posts

**Comment by ngdream** [comment]
> @ngdream I seem to have some errors can you help me solve it out? #67

ok bro

**Comment by ngdream** [comment]
can we talk on disord instead ??

**Comment by ishaan010** [comment]
Ya sure

**Comment by ishaan010** [comment]
Hey guys, I am just going to assing you all some roles so we can manage ezpie more easily.

1. @ngdream and I will maintian the code
2. @Bhavil-13 will update documents
3. And we all will be adding blogs(of course).

By the way I installed @all-contributors app. It's cool I tryed it and it works awesome. Here's a demo

@all-contributors
please add @ngdream  for code, content and maintenance.
please add @Bhavil-13  for content, doc and translation.

**Comment by ishaan010** [comment]
See really cool!

**Comment by ngdream** [comment]
> Hey guys, I am just going to assing you all some roles so we can manage ezpie more easily.
> 
> 1. @ngdream and I will maintian the code
> 2. @Bhavil-13 will update documents
> 3. And we all will be adding blogs(of course).
> 
> By the way I installed @all-contributors app. It's cool I tryed it and it works awesome. Here's a demo
> 
> @all-contributors please add @ngdream for code, content and maintenance. please add @Bhavil-13 for content, doc and translation.

@ishaan010  hey when will you be connected on discord we should chat there

**Comment by ishaan010** [comment]
> > Hey guys, I am just going to assing you all some roles so we can manage ezpie more easily.
> > 
> > 1. @ngdream and I will maintian the code
> > 2. @Bhavil-13 will update documents
> > 3. And we all will be adding blogs(of course).
> > 
> > By the way I installed @all-contributors app. It's cool I tryed it and it works awesome. Here's a demo
> > @all-contributors please add @ngdream for code, content and maintenance. please add @Bhavil-13 for content, doc and translation.
> 
> @ishaan010 hey when will you be connected on discord we should chat there

Any time you are good with
